In [133]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [39]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
import joblib

In [40]:
df = pd.read_csv("synthetic_soil_crop_dataset.csv")
df.head()

        N       P       K  temperature  humidity    ph  rainfall      label
0   52.44   60.11   79.73        27.49     68.40  4.05    198.68  blackgram
1  133.10   71.28   71.58        36.14     24.76  3.86    148.60       jute
2  102.48  124.64   40.23        29.69     37.73  7.13    290.06     papaya
3   83.81   52.60  126.45        12.92     63.06  9.30     81.31   mungbean
4   21.84  126.75  100.32        16.50     48.57  6.52    184.60  blackgram

In [41]:
le = LabelEncoder()
df['label'] = le.fit_transform(df['label'])

In [42]:
df

           N       P       K  temperature  humidity    ph  rainfall  label
0      52.44   60.11   79.73        27.49     68.40  4.05    198.68      2
1     133.10   71.28   71.58        36.14     24.76  3.86    148.60      8
2     102.48  124.64   40.23        29.69     37.73  7.13    290.06     17
3      83.81   52.60  126.45        12.92     63.06  9.30     81.31     14
4      21.84  126.75  100.32        16.50     48.57  6.52    184.60      2
...      ...     ...     ...          ...       ...   ...       ...    ...
4995  125.64  125.07  135.18        40.70     36.20  9.21    141.63      9
4996   16.71  130.65   40.56        11.64     68.16  7.99    149.80     11
4997   45.90  137.54   15.25        20.63     83.86  3.62    168.31     19
4998  114.20   60.65  141.59        25.52     60.98  5.91    290.92     12
4999   83.62   35.40   55.22        16.03     86.15  5.04    273.31      8

[5000 rows x 8 columns]

In [74]:
input_data = df.drop(['label'], axis=1)
output_data = df['label']

In [75]:
X_train, X_test, y_train, y_test=train_test_split(input_data,output_data, test_size=0.2, random_state=42)

model=RandomForestClassifier(n_estimators=150,max_depth=18,min_samples_split=10,min_samples_leaf=3,random_state=42)
model.fit(input_data,output_data)

RandomForestClassifier(max_depth=18, min_samples_leaf=3, min_samples_split=10,
                       n_estimators=150, random_state=42)

In [68]:
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")

Model Accuracy: 0.99

In [76]:
train_score=model.score(X_train, y_train)
test_score=model.score(X_test, y_test)

In [77]:
train_score

0.99125

In [78]:
test_score

0.993